@startmindmap
+ 链配置
++ 链级配置
+++ genesis
++++ timestamp
++++ prevhash
+++ system_config
++++ version
++++ chain_id
++++ admin
++++ block_interval
++++ validators
++++ block_limit
+++ 节点网络地址列表
++++ host
++++ port
++++ domain（同时用于证书和节点文件夹名称）
+++ 六个微服务的名称和版本
+++ 如果network为tls
++++ 根证书
++++ 节点证书
++ 节点配置
+++ controller
++++ network_port
++++ consensus_port
++++ executor_port
++++ storage_port
++++ controller_port
++++ kms_port
++++ key_id
++++ node_address
++++ quota_limit
+++ network
++++ network_p2p
+++++ port
+++++ grpc_port
+++++ peers（multi-address）
++++ network_tls
+++++ grpc_port
+++++ listen_port
+++++ reconnect_timeout
+++++ ca_cert
+++++ cert
+++++ priv_key
+++++ peers（host/port/domain）
+++ consensus
++++ consensus_raft
+++++ network_port
+++++ controller_port
+++++ node_addr
+++++ grpc_listen_port
++++ consensus_bft
+++++ controller_port
+++++ consensus_port
+++++ network_port
+++++ kms_port
+++++ node_address
+++ executor
++++ executor_evm
+++++ executor_port
+++ kms
++++ kms_sm
+++++ kms_port
+++++ db_key
++++ kms_eth
+++++ kms_port
+++++ db_key
+++ storage
++++ storage_rocksdb
+++++ kms_port
+++++ storage_port
+++ log
++++ log_level
++++ is_stdout
++ 杂项
+++ config-dir
+++ chain_name
@endmindmap
